config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users do
    resources :profiles, only: [:new, :create, :edit, :update]
  end
  resources :venues do
    member do
      get 'employees'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates :first_name, presence: :true
  validates :last_name, presence: :true
  validates :date_of_birth, presence: :true
  validates :gender, presence: :true,
            inclusion: { in: %w(Male Female) , message: "%{value} is not a valid gender" }
  validate :validate_age

  belongs_to :user, dependent: :destroy

  def validate_age
    if date_of_birth.present? && date_of_birth > Date.today - 19.years
      errors.add(:base, "Sorry, you are not old enough to sign up.")
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: :true, uniqueness: { case_sensitive: false }

  has_one :profile, dependent: :destroy
  has_many :venues, foreign_key: :owner_id
end

app/models/venue.rb
class Venue < ApplicationRecord
  resourcify

  validates :name, presence: true
  validates :location, presence: true
  validates :age, presence: true
  validates :owner_id, presence: true

  belongs_to :owner, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :is_logged_in?
  skip_before_action :is_logged_in?, if: :devise_controller?
  before_action :has_profile?
  skip_before_action :has_profile?, if: :devise_controller?

  private
    def is_logged_in?
      unless current_user
        redirect_to new_user_session_path, notice: 'Please sign in.'
      end
    end

    def is_admin?
      unless current_user and current_user.admin
        redirect_to root_path, notice: 'You do not have permission for that page.'
      end
    end

    def is_owner?
      unless current_user and (current_user == @venue.owner or current_user.admin)
        redirect_to @venue, notice: 'You do not have permission for that page.'
      end
    end

    def has_profile?
      unless current_user and current_user.profile
        redirect_to new_user_profile_path(current_user), notice: "Please fill out your profile first."
      end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :is_users_profile?, only: [:edit, :update]
  skip_before_action :has_profile?

  def new
    @profile = current_user.build_profile
  end

  def edit
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to current_user, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to current_user, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def is_users_profile?
      unless @profile == current_user.profile
        redirect_to current_user, notice: 'You do not have access to that page.'
      end
    end

    def profile_params
      params.require(:profile).permit(:username, :first_name, :last_name, :gender, :date_of_birth)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_user_profile_path(current_user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :is_logged_in?
  skip_before_action :has_profile?

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    unless user == current_user
      redirect_to current_user
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy, :employees, :add_employee]
  before_action :is_admin?, only: [:new, :create, :destroy]
  before_action :is_owner?, only: [:edit, :update, :employees, :add_employee]

  def index
    @venues = Venue.all
  end

  def show
  end

  def new
    @venue = Venue.new
  end

  def edit
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to @venue, notice: 'Venue was successfully created.'
    else
      render :new
    end
  end

  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: 'Venue was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_url, notice: 'Venue was successfully destroyed.'
  end

  def employees
    @users = User.with_role(:employee, @venue)

    if params[:email]
      @user = User.find_by(email: params[:email])
      if @user and @user.has_role?(:employee, @venue)
        return redirect_to employees_venue_path(@venue),
               notice: "#{@user.email} is already employeed."
      end
    end

    if params[:delete_user]
      user = User.find(params[:delete_user])
      user.remove_role(:employee, @venue)
      redirect_to employees_venue_path(@venue), notice: "#{user.email} was removed as an employee."
    end

    if params[:add_user]
      user = User.find(params[:add_user])
      if user.has_role?(:employee, @venue)
        return redirect_to employees_venue_path(@venue),
               notice: "#{user.email} is already employeed."
      end
      user.add_role(:employee, @venue)
      redirect_to employees_venue_path(@venue), notice: "#{user.email} was added as an employee."
    end
  end

  private
    def set_venue
      @venue = Venue.find(params[:id])
    end

    def venue_params
      params.require(:venue).permit(:name, :location, :age, :email, :phone, :capacity,
                                    :music, :dress_code, :website, :category, :owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/_nav_bar.html.erb
<%= link_to "Venues", venues_path %>
<% if current_user %>
  <%= link_to "Profile", current_user %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clubbing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav_bar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, url: user_profiles_path(current_user), local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %><br />
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :first_name %><br />
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %><br />
    <%= form.date_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :gender %><br />
    <%= form.select :gender, options_for_select(['Male', 'Female']) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/static_pages/home.html.erb
<h1>Home</h1>

app/views/users/show.html.erb
<% if current_user.profile %>
  <%= link_to "Edit Profile", edit_user_profile_path(current_user) %>
<% else %>
  <%= link_to "Add Profile", new_user_profile_path(current_user) %>
<% end %>

<% if current_user.profile %>
  <li><%= current_user.profile.username %></li>
  <li><%= current_user.profile.first_name %></li>
  <li><%= current_user.profile.last_name %></li>
  <li><%= current_user.profile.gender %></li>
  <li><%= current_user.profile.date_of_birth %></li>
<% end %>

app/views/venues/_form.html.erb
<%= form_with(model: venue, local: true) do |form| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :music %>
    <%= form.text_field :music %>
  </div>

  <div class="field">
    <%= form.label :dress_code %>
    <%= form.text_field :dress_code %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.collection_select(:owner_id, User.all, :id, :email) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/venues/_owner_bar.html.erb
<% if current_user == @venue.owner || current_user && current_user.admin %>
  <!-- new event -->
  <%= link_to "Employees", employees_venue_path(@venue) %>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %>

app/views/venues/employees.html.erb
<%= form_tag employees_venue_path(@venue), method: :get do %>
  <p>enter email</p>

  <div class="field">
    <%= text_field_tag :email %>
  </div>

  <div class="actions">
    <%= submit_tag "Search" %>
  </div>
<% end %>

<% if @user.present? %>
  <%= form_tag employees_venue_path(@venue), method: :get do |form| %>
    <% unless @user.profile.present? %>
      <li>
          <%= @user.profile.first_name %> <%= @user.profile.last_name %>
      </li>
    <% end %>

    <li><%= @user.email %></li>

    <%= hidden_field_tag :add_user, @user.id %>

    <li><%= submit_tag "Add Employee" %></li>
  <% end %>
<% end %>

<ul>
  <% @users.each do |user| %>
    <%= form_tag employees_venue_path(@venue), method: :get do |form| %>
      <% unless user.profile.present? %>
        <li>
            <%= user.profile.first_name %> <%= user.profile.last_name %>
        </li>
      <% end %>

        <li><%= user.email %></li>

        <%= hidden_field_tag :delete_user, user.id %>

        <li><%= submit_tag "Delete Employee" %></li>
    <% end %>
  <% end %>
</ul>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Venues</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <ul>
        <%= link_to venue do %>
          <li><%= venue.name %></li>
        <% end %>
        <li><%= venue.location %></li>
        <li><%= venue.age %></li>
      </ul>
    <% end %>
  </tbody>
</table>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

app/views/venues/show.html.erb
<%= render 'owner_bar' %>
<ul>
  <li><%= @venue.name %></li>
  <li><%= @venue.location %></li>
  <li><%= @venue.age %></li>
  <li><%= @venue.email %></li>
  <li><%= @venue.phone %></li>
  <li><%= @venue.capacity %></li>
  <li><%= @venue.music %></li>
  <li><%= @venue.dress_code %></li>
  <li><%= @venue.website %></li>
  <li><%= @venue.category %></li>
  <li><%= @venue.owner.email %></li>
</ul>

<%= link_to 'Edit', edit_venue_path(@venue) %>